### ISSUE TITLE
Strange jump in plots on the edge of subdomains

### ISSUE THREAD

**Issue by MakisH** [klicperajo/turbulent#2]
A picture that shows what we discussed. This is for 2D dns with uniform mesh, 2x2 procs, 50x50 cells. I attach also sample vtk files.

![plot_jumps](https://cloud.githubusercontent.com/assets/4943683/11715418/055a4d58-9f42-11e5-92cc-20204a16c7bf.png)
[par_cav2D_unif_dns_50_50.zip](https://github.com/klicperajo/turbulent/files/58062/par_cav2D_unif_dns_50_50.zip)

**Comment by tpaula** [comment]
It really is a ParaView issue. I created a new plot for which I extracted the data from each subdomain separately (plot is attached). We can see that there are no jumps (except that there is no line connecting the curves in the middle as they are separate plots). It seems that in the grouped DataSet ParaView changes the underlying data from which it interpolates at the domain boundary. So it jumps from orange->pink, blue->green and red->black (considering the colors from my plot).

Color legend:
- green/pink/black corresponds to upper two subdomains
- blue/orange/red corresponds to lower two subdomains
  (Don't be confused by the numbers on the x-axis. I had to change it to show the index of the interpolation point, otherwise it would not show the curves nicely in one plot.)

I hope that helps understanding the issue a bit. At least it should help us ignoring/avoiding it.

![par_cavity2d_step](https://cloud.githubusercontent.com/assets/15674612/11721703/79f0045a-9f65-11e5-9408-0fec9bb77447.png)
